engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
            mass_threshold: 50
  eslint:
    enabled: true
  csslint:
    enabled: true

ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"